#!/bin/sh
#
# Names that a platform takes for itself, the ones a Termina identifier may not
# reuse. A generated .c includes nothing but <termina.h>, so what it collides
# with is whatever that one header drags in: the OSAL API, the standard headers
# it uses, and everything those pull behind them. The probe below is that
# translation unit, compiled by the platform's own compiler with the platform's
# own flags, which is where index() comes from on posix-gcc and rtems5.
#
# Two extractions:
#
#   the declarations, from -aux-info under gcc and from the AST dump under
#   clang, which has no -aux-info
#   -E -dM, every macro that survives the preprocessor
#
# The gcc path reports functions alone, so the typedef names and the objects of
# the standard are left to the fixed list of Semantic/Reserved.hs, where they
# belong anyway because they do not change from platform to platform.
#
# Identifiers that start with an underscore are dropped: the rule about them is
# a pattern in the fixed list, so carrying a few hundred __builtin_* names as
# data buys nothing.
#
# Usage: gen-reserved.sh <platform> [output]
#
#   ./gen-reserved.sh posix-gcc
#   TERMINA_OSAL_DIR=/opt/termina-osal ./gen-reserved.sh rtems5-leon3-nexysa7 rtems5.txt
#
# EXTRA_CFLAGS goes after the flags of the platform, to see what a define of
# one's own changes: with -D_DEFAULT_SOURCE newlib and glibc declare the names
# of POSIX that they hide otherwise, index() among them.
#
# The three platforms need their three toolchains, so the lists that are
# committed come from the docker-termina image, which pins all of them together
# with the OSAL.

set -eu

PLATFORM="${1:?usage: gen-reserved.sh <platform> [output]}"
OUTPUT="${2:-}"

HERE=$(cd "$(dirname "$0")" && pwd)
TERMINA_OSAL_DIR="${TERMINA_OSAL_DIR:-/opt/termina-osal}"
export TERMINA_OSAL_DIR

ask() {
    make -s -f "$HERE/probe.mk" PLATFORM="$PLATFORM" "print-$1" | tail -1
}

CC=$(ask CC)
CFLAGS="$(ask CFLAGS) ${EXTRA_CFLAGS:-}"
INCLUDE_DIRS=$(ask INCLUDE_DIRS)

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo '#include <termina.h>' > "$WORK/probe.c"

# | termina.h opens with the config.h that a build generates for its project.
# The probe declares no object of its own, so the counters are all zero.
cat > "$WORK/config.h" <<'EOF'
#ifndef __CONFIG_H__
#define __CONFIG_H__
#define __TERMINA_APP_CONFIG_POOLS 0
#define __TERMINA_APP_CONFIG_TASKS 0
#define __TERMINA_APP_CONFIG_PERIODIC_TIMERS 0
#define __TERMINA_APP_CONFIG_MUTEXES 0
#define __TERMINA_APP_CONFIG_MESSAGE_QUEUES 0
#define __TERMINA_APP_CONFIG_MESSAGE_BUFFER_MEMORY 0
#define __TERMINA_MICROSECONDS_PER_TICK 10000
#endif
EOF

INCS="-I$WORK"
for dir in $INCLUDE_DIRS; do
    INCS="$INCS -I$dir"
done

if $CC --version | head -1 | grep -qi clang; then
    # shellcheck disable=SC2086
    $CC $CFLAGS $INCS -fsyntax-only -Xclang -ast-dump "$WORK/probe.c" > "$WORK/decls.txt"
    # | One line per declaration of the unit, the ones of the top level flush
    # against the left margin. The name is the last token before the type,
    # which the dump prints quoted.
    sed -n "s/^[|\`]-[A-Za-z]*Decl [^']* \([A-Za-z_][A-Za-z0-9_]*\) '.*\$/\1/p" \
        "$WORK/decls.txt" > "$WORK/decls.names"
else
    # shellcheck disable=SC2086
    $CC $CFLAGS $INCS -fsyntax-only -aux-info "$WORK/decls.aux" "$WORK/probe.c"
    # | A declaration line ends in the parameter list, so the name is the token
    # right before the opening parenthesis.
    sed -n 's/^.*\*\/ extern .*[ *]\([A-Za-z_][A-Za-z0-9_]*\) *(.*$/\1/p' \
        "$WORK/decls.aux" > "$WORK/decls.names"
fi

# shellcheck disable=SC2086
$CC $CFLAGS $INCS -E -dM "$WORK/probe.c" > "$WORK/macros.txt"

{
    cat "$WORK/decls.names"
    sed -n 's/^#define \([A-Za-z_][A-Za-z0-9_]*\).*$/\1/p' "$WORK/macros.txt"
} | grep -v '^_' | sort -u > "$WORK/names.txt"

emit() {
    echo "# Names taken by the $PLATFORM platform, generated by tools/reserved/gen-reserved.sh."
    echo "# Compiler: $($CC --version | head -1)"
    echo "# Flags: $CFLAGS"
    echo "# Names: $(wc -l < "$WORK/names.txt" | tr -d ' ')"
    cat "$WORK/names.txt"
}

if [ -n "$OUTPUT" ]; then
    emit > "$OUTPUT"
    echo "$OUTPUT: $(wc -l < "$WORK/names.txt" | tr -d ' ') names"
else
    emit
fi
