#ifndef TERMINA__APP_H__
#define TERMINA__APP_H__

#include <termina/types.h>
#include <termina/prelude.h>

/**
 * This file includes the declarations of the application-specific 
 * functions that shall be generated by the transpiler and that
 * will be called from the operating system abstraction layer.
 */

/**
 * \brief Initializes the application.
 * 
 * This function will be generated by the transpiler and will contain the
 * initialization code for the application.
 */
void termina__app__init(int32_t * const status);

/**
 * \brief Initializes the global objects of the application.
 *
 * This function will be generated by the transpiler and will contain the
 * initialization of the fields of the global resources, tasks, handlers and
 * emitters. It is called from termina__app__init.
 */
void termina__app__init_globals(void);

#endif // TERMINA__APP_H__
