#ifndef __TERMINA__APP_H__
#define __TERMINA__APP_H__

#include <termina/types.h>
#include <termina/prelude.h>

/**
 * This file includes the declarations of the application-specific 
 * functions that shall be generated by the transpiler and that
 * will be called from the operating system abstraction layer.
 */

/**
 * \brief Initializes the application.
 * 
 * This function will be generated by the transpiler and will contain the
 * initialization code for the application.
 */
void __termina_app__init(Status * const status);

#endif // __TERMINA__APP_H__