#ifndef TERMINA__OS__POSIX__TIMER_H__
#define TERMINA__OS__POSIX__TIMER_H__

#include <termina.h>

#include <termina/shared/list/list.h>

/**
 * \brief The list of currently active POSIX timers.
 */
extern termina__shared__list_t termina__posix__timers_list;

/**
 * \brief The list of currently blocked tasks waiting for a delay to expire.
 */
extern termina__shared__list_t termina__posix__delayed_tasks_list;

/**
 * \brief Initializes the timing services.
 */
void termina__posix__time__init(void);

/**
 * \brief Tick signal handler.
 *
 * This function is called when the tick signal is received. The tick signal is
 * generated by the tick task, which is a task that periodically sends a signal
 * to the current task.
 */
void termina__posix__time__tick_handler(int signum);

/**
 * \brief This function returns the number of ticks per second.
 */
static inline uint64_t termina__posix__time__ticks_per_sec(void) {
    return 1000000U / TERMINA__TIME__MICROSECONDS_PER_TICK;
}

/**
 * \brief Returns the current time in timeval format.
 * 
 * @param[out] timeval  the timeval structure.
 */
void termina__posix__time__get_current_time(TimeVal * const timeval);

#endif // TERMINA__OS__POSIX__TIMER_H__
