
#include <rtems.h>

#include <termina.h>

rtems_task Init(rtems_task_argument _ignored) {

    Status status;
    status.__variant = Status__Success;

    __termina_app__init(&status);

    rtems_task_delete(RTEMS_SELF);

}

#define __TERMINA_APP_CONFIG_MESSAGE_QUEUE_BUFFER CONFIGURE_MESSAGE_BUFFERS_FOR_QUEUE

#define CONFIGURE_MAXIMUM_TASKS (__TERMINA_APP_CONFIG_TASKS + 1)
#define CONFIGURE_MAXIMUM_MESSAGE_QUEUES (__TERMINA_APP_CONFIG_MESSAGE_QUEUES)
#define CONFIGURE_MAXIMUM_TIMERS (__TERMINA_APP_CONFIG_PERIODIC_TIMERS)
#define CONFIGURE_MAXIMUM_SEMAPHORES (__TERMINA_APP_CONFIG_MUTEXES)

#define CONFIGURE_MESSAGE_BUFFER_MEMORY __TERMINA_APP_CONFIG_MESSAGE_BUFFER_MEMORY

#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_MICROSECONDS_PER_TICK (__TERMINA_MICROSECONDS_PER_TICK)

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#define CONFIGURE_INIT

#include <rtems/confdefs.h>