#ifndef __CONFIG_H__
#define __CONFIG_H__

#define __TERMINA_APP_CONFIG_POOLS 1

#define __TERMINA_APP_CONFIG_TASKS 0

#define __TERMINA_APP_CONFIG_PERIODIC_TIMERS 0

#define __TERMINA_APP_CONFIG_MUTEXES 0

#define __TERMINA_APP_CONFIG_MESSAGE_QUEUES 0
#define __TERMINA_APP_CONFIG_MESSAGE_BUFFER_MEMORY 0

#define __TERMINA_MICROSECONDS_PER_TICK 10000

#define __TERMINA_CONFIG_SYS_PRINT_BUFFER_SIZE 256

#endif // __CONFIG_H__
