
#include <rtems.h>

#include <termina.h>

#define TERMINA__APP_CONFIG__MESSAGE_QUEUE_BUFFER CONFIGURE_MESSAGE_BUFFERS_FOR_QUEUE

#define CONFIGURE_MAXIMUM_TASKS (TERMINA__APP_CONFIG__TASKS + 1)
#define CONFIGURE_MAXIMUM_MESSAGE_QUEUES (TERMINA__APP_CONFIG__MESSAGE_QUEUES)
#define CONFIGURE_MAXIMUM_TIMERS (TERMINA__APP_CONFIG__PERIODIC_TIMERS)
#define CONFIGURE_MAXIMUM_SEMAPHORES (TERMINA__APP_CONFIG__MUTEXES)

#define CONFIGURE_MESSAGE_BUFFER_MEMORY TERMINA__APP_CONFIG__MESSAGE_BUFFER_MEMORY

#define CONFIGURE_APPLICATION_DOES_NOT_NEED_CONSOLE_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_MICROSECONDS_PER_TICK (TERMINA__TIME__MICROSECONDS_PER_TICK)

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#define CONFIGURE_INIT

#include <rtems/confdefs.h>

rtems_task Init(rtems_task_argument _ignored) {

    int32_t status = 0;

    (void)_ignored;

    termina__app__init(&status);

    rtems_task_delete(RTEMS_SELF);

}
